sudo: required

language: php

addons:
  apt:
    packages:
    - libevent-dev

php:
  - 7.1
  - 7.2
  - 7.3

install:
  - composer update -n --prefer-dist
  - vendor/amphp/amp/travis/install-event.sh

script:
  - vendor/bin/phpunit

cache:
  directories:
    - $HOME/.composer/cache/files
