#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

cd "$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

if [[ $# -gt 0 ]]; then
    vendor/bin/php-cs-fixer fix --config=.php_cs --path-mode=intersection "$@"
else
    vendor/bin/php-cs-fixer fix --config=.php_cs
fi
